"use client";
import { FormEvent, useState } from "react";
import { applyTravelEdit, baseTrace, demoTrip, TripPlan } from "./trip-data";

type Message={role:"agent"|"user";text:string};
type Trace={name:string;detail:string;code:string};

export function TripStudio(){
 const [trip,setTrip]=useState<TripPlan>(demoTrip); const [day,setDay]=useState(0); const [input,setInput]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [messages,setMessages]=useState<Message[]>([{role:"agent",text:"我根据慢节奏、秋日风景与美食偏好，准备了一份 4 天京都行程。你可以直接告诉我想改哪里。"}]);
 const [trace,setTrace]=useState<Trace[]>(baseTrace); const current=trip.days[day];
 async function submit(value?:string){const q=(value??input).trim();if(!q||busy)return;setInput("");setMessages(m=>[...m,{role:"user",text:q}]);setBusy(true);await new Promise(r=>setTimeout(r,450));const result=applyTravelEdit(trip,q);setTrip(result.trip);setMessages(m=>[...m,{role:"agent",text:result.message}]);setTrace(t=>[{name:result.skill,detail:`解析并应用：“${q}”`,code:`TripPlan v${trip.version} → v${result.trip.version}`},{name:"validate-itinerary",detail:"重新检查预算、时间与动线影响",code:"patch accepted · reversible"},...t].slice(0,6));setBusy(false)}
 async function share(){setError("");try{const res=await fetch("/api/trips",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip})});const data=await res.json() as {token?:string;error?:string};if(!res.ok||!data.token)throw new Error(data.error||"创建失败");const url=`${location.origin}/share/${data.token}`;await navigator.clipboard?.writeText(url);setMessages(m=>[...m,{role:"agent",text:"分享链接已创建并复制。好友打开后会看到脱敏的只读行程。"}]);window.open(url,"_blank")}catch(e){setError(e instanceof Error?e.message:"暂时无法创建分享链接")}}
 return <main className="shell">
  <header className="topbar"><div className="brand"><div className="brand-mark"><span>⌁</span></div>漫游策 Wanderplan</div><div className="top-actions"><span className="pill">TripPlan v{trip.version} · 已自动保存</span><button className="button secondary" onClick={()=>setTrip(demoTrip)}>恢复示例</button><button className="button orange" onClick={share}>分享给好友</button></div></header>
  <div className={`workspace ${busy?"loading":""}`}>
   <section className="panel chat"><p className="panel-title">与行程顾问对话</p><div className="chat-intro"><span className="eyebrow">Travel, shaped by conversation</span><h1>把想去的地方，聊成一段旅程。</h1><p>说出偏好，我会局部修改行程，并展示每一步 Skill 如何协作。</p></div><div className="messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.text}</div>)}</div><div className="suggestions">{["行程轻松一点","第三天改成雨天方案","第二天下午加个咖啡馆","预算再省一点"].map(x=><button className="suggestion" key={x} onClick={()=>submit(x)}>{x}</button>)}</div><form className="composer" onSubmit={(e:FormEvent)=>{e.preventDefault();submit()}}><input aria-label="输入行程修改要求" value={input} onChange={e=>setInput(e.target.value)} placeholder="例如：第三天下雨，换成室内活动…"/><button className="send" aria-label="发送">↑</button></form>{error&&<div className="error">{error}</div>}</section>
   <section className="panel itinerary"><div className="trip-head"><div><span className="eyebrow">Your itinerary</span><h2>{trip.title}</h2><div className="trip-meta">{trip.dates} · {trip.travelers} · 慢节奏</div></div><div className="budget"><span>预计总预算</span><strong>¥{trip.budget.toLocaleString()}</strong><span>不含往返大交通</span></div></div><div className="day-tabs">{trip.days.map((d,i)=><button key={d.date} className={`day-tab ${day===i?"active":""}`} onClick={()=>setDay(i)}>D{i+1} · {d.date}</button>)}</div><div className="day-summary"><div><h3>{current.theme}</h3><p>{current.weekday} · {current.area}</p></div><div className="weather">☀ {current.weather}</div></div><div className="timeline">{current.activities.map(a=><div className="activity" key={a.id}><div className="time">{a.time}</div><div className="rail"><span className="dot"/></div><div className="activity-copy"><h4>{a.title}</h4><p>{a.detail}</p><span className="tag">{a.tag}</span></div><div className="cost">{a.cost?`¥${a.cost}`:"免费"}</div></div>)}</div><div className="notice">✦ {trip.notices[0]}</div></section>
   <aside className="panel trace"><div className="trace-header"><p className="panel-title">Skill 编排轨迹</p><span className="live">运行中</span></div><div className="trace-list">{trace.map((t,i)=><div className={`trace-card ${i===0?"active":""}`} key={`${t.name}-${i}`}><div className="trace-top"><span className="skill-name">{t.name}</span><span className="status">✓ 完成</span></div><p>{t.detail}</p><code>{t.code}</code></div>)}</div><div className="version"><span>可撤销的结构化修改</span><span>v{trip.version}</span></div></aside>
  </div>
 </main>
}
