"use client";
import {FormEvent,useMemo,useState} from "react";
import {baseTrace,demoTrip,type Trace,type TripChange,type TripPlan} from "./trip-data";
type Message={role:"agent"|"user";text:string};type AgentResponse={message:string;trip:TripPlan|null;trace:Trace[];changes:TripChange[];usage:Array<{model:string}>;error?:string};
const skillLabels:Record<string,string>={"collect-trip-needs":"理解旅行需求","research-destination":"查询目的地信息","compose-itinerary":"安排每日路线","revise-itinerary":"调整现有行程","validate-itinerary":"检查行程可行性","share-trip":"生成只读分享"};

export function TripStudio(){
 const[trip,setTrip]=useState<TripPlan>(demoTrip),[previous,setPrevious]=useState<TripPlan|null>(null),[changes,setChanges]=useState<TripChange[]>([]),[day,setDay]=useState(0),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[developer,setDeveloper]=useState(false);
 const[messages,setMessages]=useState<Message[]>([{role:"agent",text:"告诉我目的地、日期、人数和预算，我会查询必要信息并生成一份能随时调整的旅行计划。"}]);const[trace,setTrace]=useState<Trace[]>(baseTrace),[model,setModel]=useState("qwen3.6-plus");const current=trip.days[Math.min(day,trip.days.length-1)];
 const totalActivities=useMemo(()=>trip.days.reduce((sum,d)=>sum+d.activities.length,0),[trip]);
 async function submit(value?:string){const q=(value??input).trim();if(!q||busy)return;setInput("");setError("");const next=[...messages,{role:"user" as const,text:q}];setMessages(next);setBusy(true);setTrace([{name:"router",label:"理解本轮意图",status:"running",detail:"正在判断是新规划、修改还是询问",code:"routing"},...baseTrace]);try{const res=await fetch("/api/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:q,trip,history:next.slice(-6)})});const data=await res.json() as AgentResponse;if(!res.ok)throw new Error(data.error||"智能体请求失败");if(data.trip){setPrevious(trip);setTrip(data.trip);setDay(d=>Math.min(d,data.trip!.days.length-1));setChanges(data.changes||[])}setTrace(data.trace?.length?data.trace:baseTrace);setModel(data.usage?.at(-1)?.model||model);setMessages(m=>[...m,{role:"agent",text:data.message||"行程已更新。"}])}catch(e){const text=e instanceof Error?e.message:"智能体暂时不可用";setError(text);setTrace(t=>t.map((x,i)=>i===0?{...x,status:"warning",detail:text}:x));setMessages(m=>[...m,{role:"agent",text:`这次没有改动行程：${text}`}])}finally{setBusy(false)}}
 function undo(){if(!previous)return;const now=trip;setTrip({...previous,version:trip.version+1});setPrevious(now);setChanges([{type:"changed",label:"已撤销上一轮修改",before:`v${now.version}`,after:`恢复为上一版内容`}]);setMessages(m=>[...m,{role:"agent",text:"已撤销上一轮修改。你仍可以再次调整。"}])}
 async function share(){setError("");try{const ownerToken=sessionStorage.getItem(`trip-owner:${trip.id}`);const res=await fetch("/api/trips",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip,ownerToken})});const data=await res.json() as {token?:string;ownerToken?:string;error?:string};if(!res.ok||!data.token)throw new Error(data.error||"创建失败");if(data.ownerToken)sessionStorage.setItem(`trip-owner:${trip.id}`,data.ownerToken);const url=`${location.origin}/share/${data.token}`;await navigator.clipboard?.writeText(url);setMessages(m=>[...m,{role:"agent",text:"只读分享链接已复制。好友可以查看行程，但不能覆盖你的版本。"}]);window.open(url,"_blank")}catch(e){setError(e instanceof Error?e.message:"暂时无法创建分享链接")}}
 return <main className="shell"><header className="topbar"><div className="brand"><div className="brand-mark"><span>⌁</span></div>漫游策</div><div className="top-actions"><span className="pill">智能规划已开启</span><button className="button secondary" onClick={()=>setDeveloper(x=>!x)}>{developer?"普通模式":"开发者模式"}</button>{previous&&<button className="button secondary" onClick={undo}>撤销修改</button>}<button className="button orange" onClick={share}>分享行程</button></div></header><div className="workspace">
 <section className="panel chat"><p className="panel-title">旅行计划助手</p><div className="chat-intro"><span className="eyebrow">Query & plan only</span><h1>说出想法，得到一份能随时修改的旅行计划。</h1><p>告诉我目的地、日期和预算。我会查询必要信息、安排每日路线，你可以继续通过对话调整并分享给同行朋友。</p></div><div className="scope-note">只提供查询与规划，不执行预订、下单或支付。</div><div className="messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.text}</div>)}{busy&&<div className="message agent thinking"><span/>正在查询信息并安排路线…</div>}</div><div className="suggestions">{["10月带父母去成都4天，预算6000元，少走路，喜欢美食","行程轻松一点，每天最多3个主要活动","第三天如果下雨，换成室内方案","把总预算降低1000元，但保留核心景点"].map(x=><button className="suggestion" key={x} onClick={()=>submit(x)} disabled={busy}>{x}</button>)}</div><form className="composer" onSubmit={(e:FormEvent)=>{e.preventDefault();submit()}}><input aria-label="输入旅行需求" value={input} onChange={e=>setInput(e.target.value)} disabled={busy} placeholder={trip===demoTrip?"例如：10月带父母去成都4天，预算6000元，少走路":"例如：删掉第二天下午的景点，增加一家安静的茶馆"}/><button className="send" aria-label="发送" disabled={busy}>↑</button></form>{error&&<div className="error">{error}</div>}</section>
 <section className="panel itinerary"><div className="trip-head"><div><span className="eyebrow">Your itinerary</span><h2>{trip.title}</h2><div className="trip-meta">{trip.dates} · {trip.travelers} · {totalActivities} 个计划节点</div></div><div className="budget"><span>当地预计支出</span><strong>¥{trip.budget.toLocaleString()}</strong><span>具体口径见预算构成</span></div></div>{trip.budgetBreakdown?.length?<div className="budget-grid">{trip.budgetBreakdown.map(x=><div key={x.label}><span>{x.label}</span><strong>¥{x.amount.toLocaleString()}</strong></div>)}</div>:null}{changes.length>0&&<div className="diff-card"><div className="diff-head"><strong>本轮调整</strong>{previous&&<button onClick={undo}>撤销</button>}</div>{changes.slice(0,5).map((c,i)=><div className={`diff-row ${c.type}`} key={`${c.label}-${i}`}><span>{c.type==="added"?"＋":c.type==="removed"?"－":"↻"}</span><div><strong>{c.label}</strong>{c.before||c.after?<small>{c.before&&`${c.before} `}{c.after&&`→ ${c.after}`}</small>:null}</div></div>)}</div>}<div className="day-tabs">{trip.days.map((d,i)=><button key={`${d.date}-${i}`} className={`day-tab ${day===i?"active":""}`} onClick={()=>setDay(i)}>D{i+1} · {d.date}</button>)}</div>{current&&<><div className="day-summary"><div><h3>{current.theme}</h3><p>{current.weekday} · {current.area}</p></div><div className="weather">{current.weather.includes("待")?"○ 参考":"● 已查询"} · {current.weather}</div></div><div className="route-card"><strong>今日路线</strong><p>{current.routeSummary||`围绕${current.area}顺路游览`}</p>{current.meals?.length?<div className="meal-list">{current.meals.map((meal,i)=><span key={`${meal}-${i}`}>🍜 {meal}</span>)}</div>:null}</div><div className="timeline">{current.activities.map(a=><div className="activity" key={a.id}><div className="time">{a.time}</div><div className="rail"><span className="dot"/></div><div className="activity-copy"><div className="activity-title"><h4>{a.title}</h4>{a.mapUrl&&<a href={a.mapUrl} target="_blank" rel="noreferrer">地图 ↗</a>}</div><p>{a.detail}</p><div className="activity-facts">{a.duration&&<span>⏱ {a.duration}</span>}{a.transport&&<span>↳ {a.transport}</span>}{a.food&&<span>🍴 {a.food}</span>}{a.tips&&<span>提示：{a.tips}</span>}</div><span className="tag">{a.tag}</span></div><div className="cost">{a.cost?`¥${a.cost}`:"免费"}</div></div>)}</div></>}{trip.sources.length>0&&<div className="source-card"><strong>查询来源</strong><p>动态信息可能变化，请在出发前打开来源复核。</p><div>{trip.sources.map((source,i)=><a href={source.url} target="_blank" rel="noreferrer" key={`${source.url}-${i}`}>{i+1}. {source.label} ↗</a>)}</div></div>}{trip.notices[0]&&<div className="notice">✦ {trip.notices[0]}</div>}</section>
 <aside className="panel trace"><div className="trace-header"><p className="panel-title">规划过程</p><span className="live">{busy?"执行中":"已就绪"}</span></div><div className="trace-list">{trace.map((t,i)=><div className={`trace-card ${t.status==="running"?"active":""}`} key={`${t.name}-${i}`}><div className="trace-top"><span className="skill-name">{t.label||skillLabels[t.name]||t.name}</span><span className={`status ${t.status}`}>{t.status==="waiting"?"等待":t.status==="running"?"执行中":t.status==="warning"?"需处理":"✓ 完成"}</span></div>{developer&&<code>{t.name} · {t.code}{t.durationMs?` · ${t.durationMs}ms`:""}</code>}<p>{t.detail}</p></div>)}</div>{developer&&<div className="developer-info"><strong>开发者信息</strong><span>模型：{model}</span><span>版本：TripPlan v{trip.version}</span><span>编排：运行时 Skill Registry</span><span>成熟能力：百炼 Web Search + FlyAI POI + 高德地图</span><span>领域 Skill：路线、美食、修改、校验、分享</span><span>模式：仅查询与规划</span></div>}</aside>
 </div></main>
}
