"use client";
import { FormEvent, useState } from "react";
import { baseTrace, demoTrip, type Trace, type TripPlan } from "./trip-data";

type Message={role:"agent"|"user";text:string};
type AgentResponse={message:string;trip:TripPlan|null;trace:Trace[];usage:Array<{model:string;promptTokens:number;completionTokens:number}>;error?:string};

export function TripStudio(){
 const [trip,setTrip]=useState<TripPlan>(demoTrip); const [day,setDay]=useState(0); const [input,setInput]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [messages,setMessages]=useState<Message[]>([{role:"agent",text:"你好，我是由百炼 API 驱动的出行规划智能体。你可以让我从头规划任何目的地，也可以直接修改右侧示例。"}]);
 const [trace,setTrace]=useState<Trace[]>(baseTrace); const [model,setModel]=useState("qwen3.6-plus"); const current=trip.days[Math.min(day,trip.days.length-1)];
 async function submit(value?:string){const q=(value??input).trim();if(!q||busy)return;setInput("");setError("");const nextMessages=[...messages,{role:"user" as const,text:q}];setMessages(nextMessages);setBusy(true);try{const res=await fetch("/api/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:q,trip,history:nextMessages.slice(-6)})});const data=await res.json() as AgentResponse;if(!res.ok)throw new Error(data.error||"智能体请求失败");if(data.trip){setTrip(data.trip);setDay(d=>Math.min(d,data.trip!.days.length-1))}setTrace(data.trace?.length?data.trace:trace);setModel(data.usage?.at(-1)?.model||model);setMessages(m=>[...m,{role:"agent",text:data.message||"行程已更新。"}])}catch(e){const text=e instanceof Error?e.message:"智能体暂时不可用";setError(text);setMessages(m=>[...m,{role:"agent",text:`这次没有改动行程：${text}`}])}finally{setBusy(false)}}
 async function share(){setError("");try{const res=await fetch("/api/trips",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trip})});const data=await res.json() as {token?:string;error?:string};if(!res.ok||!data.token)throw new Error(data.error||"创建失败");const url=`${location.origin}/share/${data.token}`;await navigator.clipboard?.writeText(url);setMessages(m=>[...m,{role:"agent",text:"分享链接已创建并复制。好友打开后会看到脱敏的只读行程。"}]);window.open(url,"_blank")}catch(e){setError(e instanceof Error?e.message:"暂时无法创建分享链接")}}
 return <main className="shell"><header className="topbar"><div className="brand"><div className="brand-mark"><span>⌁</span></div>漫游策 Wanderplan</div><div className="top-actions"><span className="pill">百炼 API · {model}</span><span className="pill">TripPlan v{trip.version}</span><button className="button secondary" onClick={()=>{setTrip(demoTrip);setDay(0);setTrace(baseTrace)}}>恢复示例</button><button className="button orange" onClick={share}>分享给好友</button></div></header><div className="workspace">
  <section className="panel chat"><p className="panel-title">与行程顾问对话</p><div className="chat-intro"><span className="eyebrow">Powered by Bailian API</span><h1>把想去的地方，聊成一段旅程。</h1><p>输入任意旅行需求。模型会规划或局部修改，工具会补充实时信息，校验器负责守住结果。</p></div><div className="messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.text}</div>)}{busy&&<div className="message agent thinking"><span/>正在调用百炼 API 并编排 Skills…</div>}</div><div className="suggestions">{["帮我规划杭州三日游，2个人预算5000元，喜欢人文和美食","行程轻松一点，每天最多3个主要活动","第三天如果下雨，换成室内方案","把总预算降低1000元，但保留核心景点"].map(x=><button className="suggestion" key={x} onClick={()=>submit(x)} disabled={busy}>{x}</button>)}</div><form className="composer" onSubmit={(e:FormEvent)=>{e.preventDefault();submit()}}><input aria-label="输入旅行需求" value={input} onChange={e=>setInput(e.target.value)} disabled={busy} placeholder="例如：规划成都四日游，或修改第三天…"/><button className="send" aria-label="发送" disabled={busy}>↑</button></form>{error&&<div className="error">{error}</div>}</section>
  <section className="panel itinerary"><div className="trip-head"><div><span className="eyebrow">Your itinerary</span><h2>{trip.title}</h2><div className="trip-meta">{trip.dates} · {trip.travelers} · 可对话修改</div></div><div className="budget"><span>预计总预算</span><strong>¥{trip.budget.toLocaleString()}</strong><span>以智能体说明为准</span></div></div><div className="day-tabs">{trip.days.map((d,i)=><button key={`${d.date}-${i}`} className={`day-tab ${day===i?"active":""}`} onClick={()=>setDay(i)}>D{i+1} · {d.date}</button>)}</div>{current&&<><div className="day-summary"><div><h3>{current.theme}</h3><p>{current.weekday} · {current.area}</p></div><div className="weather">☀ {current.weather}</div></div><div className="timeline">{current.activities.map(a=><div className="activity" key={a.id}><div className="time">{a.time}</div><div className="rail"><span className="dot"/></div><div className="activity-copy"><h4>{a.title}</h4><p>{a.detail}</p><span className="tag">{a.tag}</span></div><div className="cost">{a.cost?`¥${a.cost}`:"免费"}</div></div>)}</div></>}{trip.notices[0]&&<div className="notice">✦ {trip.notices[0]}</div>}</section>
  <aside className="panel trace"><div className="trace-header"><p className="panel-title">Skill 编排轨迹</p><span className="live">API 模式</span></div><div className="trace-list">{trace.map((t,i)=><div className={`trace-card ${i===0?"active":""}`} key={`${t.name}-${i}`}><div className="trace-top"><span className="skill-name">{t.name}</span><span className="status">✓ 完成</span></div><p>{t.detail}</p><code>{t.code}</code></div>)}</div><div className="version"><span>结构化、可验证、可分享</span><span>v{trip.version}</span></div></aside>
 </div></main>
}
