import type {ActivityLocation,ActivityRoute,TripPlan} from "../app/trip-data";

type AmapPoi={id:string;name:string;address:string|string[];location:string;citycode?:string};
type AmapSearchResponse={status:string;info?:string;pois?:AmapPoi[]};
type AmapRouteResponse={status:string;info?:string;route?:{paths?:Array<{distance?:string;cost?:{duration?:string}}>}};

function toLocation(poi:AmapPoi):ActivityLocation|null{const [longitude,latitude]=poi.location.split(",").map(Number);if(!Number.isFinite(longitude)||!Number.isFinite(latitude))return null;return {longitude,latitude,poiId:poi.id,address:Array.isArray(poi.address)?poi.address.join(" "):poi.address||"",source:"amap"}}
function straightDistance(a:ActivityLocation,b:ActivityLocation){const rad=(value:number)=>value*Math.PI/180;const earth=6371000,lat1=rad(a.latitude),lat2=rad(b.latitude),dLat=lat2-lat1,dLng=rad(b.longitude-a.longitude);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return Math.round(earth*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)))}
async function amapGet<T>(path:string,params:Record<string,string>){const url=new URL(`https://restapi.amap.com${path}`);for(const [key,value] of Object.entries(params))url.searchParams.set(key,value);const response=await fetch(url,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`高德 API HTTP ${response.status}`);return await response.json() as T}
async function searchPoi(key:string,destination:string,title:string){const result=await amapGet<AmapSearchResponse>("/v3/place/text",{key,keywords:`${destination} ${title}`,city:destination,citylimit:"true",offset:"3",page:"1",extensions:"base"});if(result.status!=="1")throw new Error(result.info||"高德 POI 搜索失败");const exact=result.pois?.find(poi=>poi.name===title)||result.pois?.[0];return exact?{poi:exact,location:toLocation(exact)}:null}
async function routeBetween(key:string,from:{poi:AmapPoi;location:ActivityLocation},to:{poi:AmapPoi;location:ActivityLocation}):Promise<ActivityRoute>{const direct=straightDistance(from.location,to.location);const mode=direct<=2500?"walking":"transit";const common={key,origin:`${from.location.longitude},${from.location.latitude}`,destination:`${to.location.longitude},${to.location.latitude}`,show_fields:"cost"};const params=mode==="transit"?{...common,city1:from.poi.citycode||"",city2:to.poi.citycode||from.poi.citycode||""}:common;if(mode==="transit"&&(!params.city1||!params.city2))return {mode:"estimated",distanceMeters:direct,source:"estimate"};try{const path=mode==="walking"?"/v5/direction/walking":"/v5/direction/transit/integrated";const result=await amapGet<AmapRouteResponse>(path,params);const route=result.route?.paths?.[0];if(result.status!=="1"||!route)return {mode:"estimated",distanceMeters:direct,source:"estimate"};const distance=Math.max(0,Math.round(Number(route.distance)||direct));const seconds=Math.max(0,Math.round(Number(route.cost?.duration)||0));return {mode,distanceMeters:distance,durationMinutes:seconds?Math.max(1,Math.round(seconds/60)):undefined,source:"amap"}}catch{return {mode:"estimated",distanceMeters:direct,source:"estimate"}}}
function mapSearchUrl(destination:string,title:string,location?:ActivityLocation){if(location)return `https://uri.amap.com/marker?position=${location.longitude},${location.latitude}&name=${encodeURIComponent(title)}&src=wanderplan&coordinate=gaode&callnative=0`;return `https://www.amap.com/search?query=${encodeURIComponent(`${destination} ${title}`)}`}
function routeText(route:ActivityRoute){const distance=route.distanceMeters<1000?`${route.distanceMeters} 米`:`${(route.distanceMeters/1000).toFixed(1)} 公里`;if(route.source==="estimate")return `两点直线距离约 ${distance}，请打开地图选择实时交通方式`;return `${route.mode==="walking"?"步行":"公共交通"}约 ${route.durationMinutes||"待核验"} 分钟（${distance}）`}

export async function enrichTripWithAmap(trip:TripPlan){
  const key=process.env.AMAP_WEB_SERVICE_KEY?.trim();
  if(!key){for(const day of trip.days)for(const activity of day.activities)activity.mapUrl=mapSearchUrl(trip.destination,activity.title);return {status:"link_only" as const,trip,resolved:0,routed:0}}
  let resolved=0,routed=0;
  for(const day of trip.days){const matches=await Promise.all(day.activities.map(activity=>searchPoi(key,trip.destination,activity.title).catch(()=>null)));for(let index=0;index<day.activities.length;index++){const activity=day.activities[index],match=matches[index];if(match?.location){activity.location=match.location;resolved++}activity.mapUrl=mapSearchUrl(trip.destination,activity.title,match?.location||undefined);const previous=index>0?matches[index-1]:null;if(previous?.location&&match?.location){const route=await routeBetween(key,previous as {poi:AmapPoi;location:ActivityLocation},match as {poi:AmapPoi;location:ActivityLocation});activity.routeFromPrevious=route;activity.transport=`高德路线：${routeText(route)}。${activity.transport||""}`.trim();if(route.source==="amap")routed++}}const names=day.activities.filter(activity=>activity.location).map(activity=>activity.title);if(names.length>=2)day.routeSummary=`${names.join(" → ")}。已用高德 POI 校验地点，并核算相邻行程；出发时请再看实时路况。`}
  return {status:"verified" as const,trip,resolved,routed};
}
