import {callBailianJson,type BailianUsage} from "./bailian";
import {runSkillPhase,selectSkills,skillPrompt} from "./skill-registry";
import type {AgentIntent,SkillContext} from "../skills/runtime-types";
import type {TripChange,TripPlan,Trace} from "../app/trip-data";

type RouterResult={intent:AgentIntent;destination:string|null;days:number|null;startDate:string|null;travelers:number|null;budget:number|null};
type ModelResult={message:string;trip:TripPlan|null;needsClarification?:boolean};
export type AgentResult=ModelResult&{usage:BailianUsage[];intent:AgentIntent;trace:Trace[];changes:TripChange[]};

const routerPrompt=`你是旅行规划意图路由器，只返回 JSON。当前日期 ${new Date().toISOString().slice(0,10)}。intent 只能是 new_trip、revise_trip、answer_trip、clarify。忠实提取 destination、days、startDate(YYYY-MM-DD)、travelers、budget；未知填 null。中文地名保持中文。用户想预订或购买时仍归入 answer_trip，因为本产品只提供查询和规划。`;
const plannerBase=`你是“漫游策”查询与规划智能体，只输出 JSON，不输出 Markdown。严格禁止执行或暗示已完成预订、下单、占座和支付；可以提供查询结果、候选建议和规划。动态事实无法核验时明确标注待核验。
TripPlan 包含 id,title,destination,dates,travelers,budget,version,days,notices,assumptions,sources,budgetBreakdown。不要输出 shareToken、ownerToken 或任何访问凭证。activity 包含 id,time,title,detail,tag,cost。source 没有可信链接时可为空，禁止编造 URL。
每个 day 必须包含 date、weekday、theme、area、weather、activities；每个 activity.time 必须严格使用两位小时的 HH:MM，例如 09:00，不能写 9:00。
输出 {"message":"...","trip":{...},"needsClarification":false}。`;

function normalize(raw:TripPlan,current:TripPlan|null,intent:AgentIntent){
 const now=Date.now().toString(36);const trip:TripPlan={...raw,id:intent==="new_trip"?`trip-${crypto.randomUUID()}`:(current?.id||raw.id||`trip-${now}`),version:intent==="new_trip"?1:intent==="revise_trip"&&current?current.version+1:(current?.version??1),budget:Math.max(0,Math.round(Number(raw.budget)||0)),notices:Array.isArray(raw.notices)?raw.notices.slice(0,8):[],assumptions:Array.isArray(raw.assumptions)?raw.assumptions.slice(0,8):[],sources:Array.isArray(raw.sources)?raw.sources.filter(s=>s?.url&&/^https?:\/\//.test(s.url)).slice(0,10):[],days:Array.isArray(raw.days)?raw.days.slice(0,7):[],budgetBreakdown:Array.isArray(raw.budgetBreakdown)?raw.budgetBreakdown.map(x=>({...x,amount:Math.max(0,Math.round(Number(x.amount)||0))})).slice(0,8):[]};
 trip.days.forEach((day,di)=>{day.date||=`第${di+1}天`;day.weekday||="";day.theme||=`${trip.destination}第${di+1}天`;day.area||=trip.destination;day.weather||="待查询";day.activities=Array.isArray(day.activities)?day.activities.slice(0,6):[];day.activities.forEach((a,ai)=>{a.id||=`d${di+1}-a${ai+1}-${now}`;if(/^\d:\d{2}$/.test(a.time))a.time=`0${a.time}`;a.cost=Math.max(0,Math.round(Number(a.cost)||0))});day.activities.sort((a,b)=>a.time.localeCompare(b.time))});
 const plannedCost=trip.days.flatMap(day=>day.activities).reduce((sum,activity)=>sum+activity.cost,0);const breakdown=trip.budgetBreakdown??[];const accounted=breakdown.reduce((sum,item)=>sum+item.amount,0);if(!breakdown.length&&trip.budget>0){trip.budgetBreakdown=[{label:"行程内活动与餐饮",amount:Math.min(plannedCost,trip.budget)}];if(plannedCost<trip.budget)trip.budgetBreakdown.push({label:"住宿、往返交通与机动",amount:trip.budget-plannedCost})}else if(accounted<trip.budget)breakdown.push({label:"机动预算",amount:trip.budget-accounted});return trip
}
function validate(trip:TripPlan){const errors:string[]=[];if(!trip.title||!trip.destination||!trip.dates||!trip.travelers)errors.push("基础字段不完整");if(!trip.days.length)errors.push("至少需要一天");const ids=new Set<string>();trip.days.forEach((d,di)=>{let last="00:00";if(!d.date||!d.theme||!d.activities.length)errors.push(`第${di+1}天不完整`);d.activities.forEach(a=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(a.time))errors.push(`${a.id}时间错误`);if(a.time<last)errors.push(`第${di+1}天顺序错误`);if(!a.id||ids.has(a.id))errors.push("活动ID缺失或重复");ids.add(a.id);last=a.time})});const budgetTotal=(trip.budgetBreakdown??[]).reduce((sum,item)=>sum+item.amount,0);if(budgetTotal>trip.budget)errors.push(`预算拆分 ${budgetTotal} 元超过总预算 ${trip.budget} 元`);return errors}
function diff(before:TripPlan|null,after:TripPlan|null):TripChange[]{if(!after)return[];if(!before)return[{type:"added",label:"创建行程",after:`${after.destination} · ${after.days.length}天 · ¥${after.budget}`}];const result:TripChange[]=[];if(before.budget!==after.budget)result.push({type:"changed",label:"总预算",before:`¥${before.budget}`,after:`¥${after.budget}`});if(before.days.length!==after.days.length)result.push({type:"changed",label:"行程天数",before:`${before.days.length}天`,after:`${after.days.length}天`});const oldMap=new Map(before.days.flatMap(d=>d.activities).map(a=>[a.id,a]));const newMap=new Map(after.days.flatMap(d=>d.activities).map(a=>[a.id,a]));for(const[id,a]of oldMap)if(!newMap.has(id))result.push({type:"removed",label:a.title});for(const[id,a]of newMap){const old=oldMap.get(id);if(!old)result.push({type:"added",label:a.title});else if(old.title!==a.title||old.time!==a.time||old.detail!==a.detail)result.push({type:"changed",label:a.title,before:`${old.time} ${old.title}`,after:`${a.time} ${a.title}`})}return result.slice(0,8)}

export async function runTripAgent(input:string,currentTrip:TripPlan|null,history:Array<{role:string;text:string}>=[]):Promise<AgentResult>{
 const route=await callBailianJson<RouterResult>({model:process.env.BAILIAN_ROUTER_MODEL||"qwen3.6-plus",maxTokens:300,temperature:0,messages:[{role:"system",content:routerPrompt},{role:"user",content:JSON.stringify({input,currentDestination:currentTrip?.destination||null,currentVersion:currentTrip?.version||null})}]});
 const selected=selectSkills(route.data.intent);const initial:SkillContext={input,intent:route.data.intent,currentTrip,destination:route.data.destination||currentTrip?.destination||null,startDate:route.data.startDate,toolResults:{}};const prepared=await runSkillPhase(selected,"prepare",initial);const planningTrip=route.data.intent==="new_trip"?null:currentTrip;
 const planningRequest={model:process.env.BAILIAN_MODEL||"qwen3.6-plus",maxTokens:6500,temperature:.12,enableSearch:true,messages:[{role:"system" as const,content:`${plannerBase}\n\n本轮实际加载的 Skills：\n${skillPrompt(selected)}`},{role:"user" as const,content:JSON.stringify({userInput:input,intent:route.data.intent,extractedConstraints:route.data,currentTrip:planningTrip,recentConversation:history.slice(-6),toolResults:prepared.context.toolResults})}]};let planned=await callBailianJson<ModelResult>(planningRequest);const usage=[route.usage,planned.usage];if(!planned.data.trip&&(route.data.intent==="new_trip"||route.data.intent==="revise_trip")){planned=await callBailianJson<ModelResult>({...planningRequest,temperature:0,messages:[...planningRequest.messages,{role:"user",content:"首次响应缺少 trip。请严格按要求返回完整、可校验的 TripPlan JSON；不要改为解释性回答。"}]});usage.push(planned.usage)}
 if(!planned.data.trip){if(route.data.intent==="clarify"||route.data.intent==="answer_trip")return{...planned.data,trip:currentTrip,usage,intent:route.data.intent,trace:prepared.trace,changes:[]};throw new Error("模型未返回可用行程")}
 let trip=normalize(planned.data.trip,currentTrip,route.data.intent);let errors=validate(trip);if(errors.length){const repaired=await callBailianJson<{trip:TripPlan}>({model:process.env.BAILIAN_MODEL||"qwen3.6-plus",maxTokens:6500,temperature:0,messages:[{role:"system",content:`你是结构化行程修复器，只返回 {"trip":{...}}。只修复列出的校验错误，保留原有内容、稳定 ID、查询边界和“只查询规划、不预订”的原则。所有时间严格使用 HH:MM。`},{role:"user",content:JSON.stringify({errors,trip})}]});usage.push(repaired.usage);trip=normalize(repaired.data.trip,currentTrip,route.data.intent);errors=validate(trip)}if(errors.length)throw new Error(`行程校验失败：${errors.slice(0,3).join("；")}`);const validated=await runSkillPhase(selected,"validate",{...prepared.context,currentTrip:trip});return{...planned.data,trip,usage,intent:route.data.intent,trace:[...prepared.trace,...validated.trace],changes:diff(route.data.intent==="new_trip"?null:currentTrip,trip)}
}
